Disable BlueMap debug logging to avoid null path error
Commented out the log file setting in core.conf as BlueMap v5.7
has an issue creating the log file causing NullPointerException.

Error: Cannot invoke "java.nio.file.Path.getFileSystem()"

This disables debug logging which is optional anyway.